  // File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNiebYgCg89T-pzniAkq93WamXS51K49A',
    appId: '1:425002886911:web:2384fba59e19c0fa698eca',
    messagingSenderId: '425002886911',
    projectId: 'learnxt-88200',
    authDomain: 'learnxt-88200.firebaseapp.com',
    storageBucket: 'learnxt-88200.appspot.com',
    measurementId: 'G-SEQ7CESYLN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxs5A4ATRnvOgrIvUiOi6NJAwb6i1TIic',
    appId: '1:425002886911:android:4a9a777758f932a9698eca',
    messagingSenderId: '425002886911',
    projectId: 'learnxt-88200',
    storageBucket: 'learnxt-88200.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRpOb2eC-jI8C72ffMnmfWOInJTm6l3AM',
    appId: '1:425002886911:ios:d0e2545a09f0b2c1698eca',
    messagingSenderId: '425002886911',
    projectId: 'learnxt-88200',
    storageBucket: 'learnxt-88200.appspot.com',
    iosBundleId: 'com.example.learnxt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRpOb2eC-jI8C72ffMnmfWOInJTm6l3AM',
    appId: '1:425002886911:ios:d0e2545a09f0b2c1698eca',
    messagingSenderId: '425002886911',
    projectId: 'learnxt-88200',
    storageBucket: 'learnxt-88200.appspot.com',
    iosBundleId: 'com.example.learnxt',
  );
}
